# # This is a basic workflow that is manually triggered


name: Test Suite

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Install Google Chrome (Latest Stable)
      shell: pwsh
      run: choco install googlechrome --no-progress --force

    - name: Install ChromeDriver using WebDriver Manager
      run: |
        python -c "from selenium import webdriver; from webdriver_manager.chrome import ChromeDriverManager; print(ChromeDriverManager().install())"

    # - name: Verify Chrome and ChromeDriver
    #   run: |
    #     chrome --version
    #     chromedriver --version
    #   shell: pwsh 
        


    - name: Run tests
      run: |
        python run_all_tests.py
