# # This is a basic workflow that is manually triggered

# name: Test Suite

# # Controls when the action will run. Workflow runs when manually triggered using the UI
# # or API.
# on:
#   push:
#     branches: [ main ]
# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   test:
#     runs-on: windows-latest
    
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: '3.10'

#     - name: Install Chrome
#       run: |
#         CHROME_VERSION="134.0.6998.165"
#         BASE_URL="https://storage.googleapis.com/chrome-for-testing-public"
    
#         # Install Chrome
#         wget "$BASE_URL/$CHROME_VERSION/linux64/chrome-linux64.zip"
#         unzip chrome-linux64.zip -d chrome
#         sudo mv chrome/chrome-linux64/chrome /usr/local/bin/google-chrome
#         sudo chmod +x /usr/local/bin/google-chrome
    
#         # Install ChromeDriver (same version)
#         wget "$BASE_URL/$CHROME_VERSION/linux64/chromedriver-linux64.zip"
#         unzip chromedriver-linux64.zip -d chromedriver
#         sudo mv chromedriver/chromedriver-linux64/chromedriver /usr/local/bin/
#         sudo chmod +x /usr/local/bin/chromedriver
    
#         # Cleanup
#         rm -rf chrome-linux64.zip chrome chromedriver-linux64.zip chromedriver
    
#         # Verify installations
#         echo "Chrome version: $(google-chrome --version)"
#         echo "ChromeDriver version: $(chromedriver --version)"
        
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install selenium webdriver-manager

#     - name: Run tests
#       run: |
#         python run_all_tests.py

name: Test Suite

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Chrome
        run: |
          choco install googlechrome --no-progress --force
        shell: pwsh

      - name: Install ChromeDriver
        run: |
          choco install chromedriver --no-progress --force
        shell: pwsh

      - name: Verify Chrome and ChromeDriver
        run: |
          chrome --version
          chromedriver --version
        shell: pwsh 
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Run tests
      run: |
        python run_all_tests.py
